included:
  - Word Bundle
  - Packages
excluded:
  - Carthage
  - Pods

disabled_rules:
  - nesting
  - weak_delegate
  - implicit_getter
  - todo
  - no_space_in_method_call
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - closing_brace
  - control_statement
  - contains_over_first_not_nil
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - convenience_type
  - empty_count
  - empty_string
  - empty_enum_arguments
  - empty_parentheses_with_trailing_closure
  - explicit_init
  - extension_access_modifier
  - prefer_zero_over_explicit_init
  - fallthrough
  - fatal_error_message
  - implicit_return
  - multiline_parameters
  - multiline_parameters_brackets
  - multiline_literal_brackets
  - multiline_arguments_brackets
  - modifier_order
  - multiline_function_chains
  - return_arrow_whitespace
  - redundant_discardable_let
  - redundant_nil_coalescing
  - statement_position
  - syntactic_sugar
  - last_where
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition


array_init: error

closure_end_indentation: error
closure_spacing: error

closing_brace: error
closure_parameter_position: error
colon:
  severity: error
comma: error
control_statement: error
compiler_protocol_init: error
contains_over_first_not_nil: error
class_delegate_protocol: error
cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: true
contains_over_filter_count: error
contains_over_filter_is_empty: error
convenience_type: error

empty_enum_arguments: error
empty_parentheses_with_trailing_closure: error
empty_string: error
explicit_init: error
prefer_zero_over_explicit_init: error

switch_case_alignment:
  severity: error

large_tuple:
  - 3
  - 4
leading_whitespace: error
line_length: 300

fallthrough: error
file_length:
  - 1000
  - 1500
force_cast: error
force_try: error
for_where: error
function_body_length:
  - 250
  - 500
function_parameter_count:
  - 10
  - 15

identifier_name:
  max_length:
    warning: 55
    error: 65
  min_length:
    warning: 1
implicit_return:
  severity: error
is_disjoint:
  severity: error

mark: error
multiple_closures_with_trailing_closure: error
multiline_function_chains: error
multiline_parameters:
  severity: error
multiline_parameters_brackets: error
multiline_literal_brackets: error
multiline_arguments_brackets: error
modifier_order:
  severity: error

operator_whitespace: error
opening_brace:
  severity: error

redundant_optional_initialization: error
return_arrow_whitespace: error
redundant_string_enum_value: error
redundant_objc_attribute: error
redundant_discardable_let: error
redundant_nil_coalescing: error

statement_position:
  severity: error
syntactic_sugar:
  severity: error
switch_case_alignment:
  severity: error

trailing_comma:
  severity: error
trailing_semicolon:
  severity: error
trailing_newline:
  severity: error
trailing_whitespace:
  severity: error
type_body_length:
  - 1000
  - 1500
type_name:
  max_length:
    warning: 65
    error: 65
  min_length:
    warning: 1

void_return: error
vertical_parameter_alignment: error
vertical_parameter_alignment_on_call: error
vertical_whitespace:
  severity: error

yoda_condition: error

